### ISSUE TITLE
proposal: aggregate support

### ISSUE THREAD

**Issue by ttzztztz** [ManiaciaChao/unique-camp-watcher#1]
1. Set a start date and generate a report from the start date to now
2. Generate an aggregate table for each person, like this:

```text
Name1: ++--++--
Name2: --++++++
```

`-` means that the person didn't commit anything that day and `+` means that the person committed that day. It will be more funny to watch these `+`, `-` symbols in the console.

**Comment by ManiaciaChao** [comment]
WIP

**Comment by ttzztztz** [comment]
`+` and `-` should be displayed in different colors
